<?php
if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array (
    'key' => 'group_57a47bdc80885',
    'title' => 'Attachments',
    'fields' => array (
      array (
        'key' => 'field_57a47c2d36cfd',
        'label' => 'Category',
        'name' => 'attachment_category',
        'type' => 'taxonomy',
        'instructions' => 'The categories are used by the General Content Module to filter the content.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'category',
        'field_type' => 'multi_select',
        'allow_null' => 0,
        'add_term' => 1,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array (
        'key' => 'field_57b1bae1039d7',
        'label' => 'Availability',
        'name' => 'attachment_availability',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => '',
        'max' => 1,
        'layout' => 'table',
        'button_label' => 'Add Availability',
        'sub_fields' => array (
          array (
            'key' => 'field_57b1baf2039d8',
            'label' => 'From',
            'name' => 'from',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'display_format' => 'd/m/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
          ),
          array (
            'key' => 'field_57b1bafc039d9',
            'label' => 'Until',
            'name' => 'until',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'display_format' => 'd/m/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
          ),
          array (
            'key' => 'field_57b1bdce15c4c',
            'label' => 'Days',
            'name' => 'days',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array (
              'monday' => 'Monday',
              'tuesday' => 'Tuesday',
              'wednesday' => 'Wednesday',
              'thursday' => 'Thursday',
              'friday' => 'Friday',
              'saturday' => 'Saturday',
              'sunday' => 'Sunday',
            ),
            'default_value' => array (
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'disabled' => 0,
            'readonly' => 0,
          ),
        ),
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'attachment',
          'operator' => '==',
          'value' => 'all',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array (
    'key' => 'group_57b1b8d5d4edc',
    'title' => 'List Page',
    'fields' => array (
      array (
        'key' => 'field_57b1b8eb9ae34',
        'label' => 'Modules',
        'name' => 'list_page_modules',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'button_label' => 'Add Module',
        'min' => '',
        'max' => '',
        'layouts' => array (
          array (
            'key' => '57b1b8e011712',
            'name' => 'attachments',
            'label' => 'Attachments',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_57b1b9029ae35',
                'label' => 'Attachments',
                'name' => 'attachments',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'block',
                'button_label' => 'Add File',
                'sub_fields' => array (
                  array (
                    'key' => 'field_57b1b9209ae36',
                    'label' => 'Attachment',
                    'name' => 'attachment',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'template-list.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
      0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array (
    'key' => 'group_57b2fa9dae260',
    'title' => 'Post Modules',
    'fields' => array (
      array (
        'key' => 'field_57b2fb004802a',
        'label' => 'External Link',
        'name' => 'external_link',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57bdb6d42f32c',
        'label' => 'Gallery Title',
        'name' => 'post_gallery_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57bdb6ef2f32e',
        'label' => 'Gallery Subtitle',
        'name' => 'post_gallery_subtitle',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57b2fade48029',
        'label' => 'Gallery',
        'name' => 'post_gallery',
        'type' => 'gallery',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => '',
        'max' => '',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'post',
        ),
      ),
      /*array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'template-contentpage.php',
        ),
      ),*/
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array (
    'key' => 'group_57a0b991e55f0',
    'title' => 'Settings',
    'fields' => array (
      array (
        'key' => 'field_57a1d98590c12',
        'label' => 'Website Logo',
        'name' => 'logo',
        'type' => 'file',
        'instructions' => 'This logo will appear on site.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => '.png, .jpg, .svg',
      ),
      array (
        'key' => 'field_57a0c10429271',
        'label' => 'Openings',
        'name' => 'opening',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 100,
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 1,
        'max' => 1,
        'layout' => 'block',
        'button_label' => 'Add Row',
        'sub_fields' => array (
          array (
            'key' => 'field_57a0c16df06fe',
            'label' => 'First Column',
            'name' => 'column_1',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 33,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
          ),
          array (
            'key' => 'field_57a0c17ff06ff',
            'label' => 'Second Column',
            'name' => 'column_2',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 33,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
          ),
          array (
            'key' => 'field_57a0c188f0700',
            'label' => 'Third Column',
            'name' => 'column_3',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 33,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
          ),
        ),
      ),
      array (
        'key' => 'field_57a9ed0ec8f2c',
        'label' => 'Category & Page Colors',
        'name' => 'category_colors',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => '',
        'max' => '',
        'layout' => 'block',
        'button_label' => 'Add Color',
        'sub_fields' => array (
          array (
            'key' => 'field_57a9ed2ac8f2d',
            'label' => 'Color',
            'name' => 'color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 33,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
          ),
          array (
            'key' => 'field_57a9ed59c8f2e',
            'label' => 'Category',
            'name' => 'category',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 33,
              'class' => '',
              'id' => '',
            ),
            'taxonomy' => 'category',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'add_term' => 1,
            'save_terms' => 0,
            'load_terms' => 0,
            'return_format' => 'id',
            'multiple' => 0,
          ),
          array (
            'key' => 'field_57a9ed8cc8f2f',
            'label' => 'Pages',
            'name' => 'pages',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 33,
              'class' => '',
              'id' => '',
            ),
            'post_type' => array (
              0 => 'page',
            ),
            'taxonomy' => array (
            ),
            'filters' => array (
              0 => 'search',
            ),
            'elements' => '',
            'min' => '',
            'max' => '',
            'return_format' => 'id',
          ),
        ),
      ),
      array (
        'key' => 'field_57a479eb3742e',
        'label' => 'General Gallery Module',
        'name' => 'general_gallery_module',
        'type' => 'gallery',
        'instructions' => 'Add all images that you want to display on any page within the gallery module. The content will be filtered automatically on each pages by the associated categories of the images.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => '',
        'max' => '',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-content-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array (
    'key' => 'group_57a1b1fce5316',
    'title' => 'SportScheck Page',
    'fields' => array (
      array (
        'key' => 'field_57a1b811a7a4c',
        'label' => 'Modules',
        'name' => 'module',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'button_label' => 'Add Module',
        'min' => '',
        'max' => '',
        'layouts' => array (
          array (
            'key' => '57a1b817881b3',
            'name' => 'section_module',
            'label' => 'Section Module',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_57a1bb1d7b0df',
                'label' => 'Section ID',
                'name' => 'id',
                'type' => 'text',
                'instructions' => 'Single word, no spaces. Underscores and dashes allowed.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33.33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a1ba0da7a4f',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33.33',
                  'class' => '',
                  'id' => '',
                ),
                'preview_size' => 'thumbnail',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'return_format' => 'array',
                'library' => 'all',
              ),
              array (
                'key' => 'field_57a1b9fca7a4e',
                'label' => 'Color',
                'name' => 'background_color',
                'type' => 'color_picker',
                'instructions' => 'Background color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33.33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '#f3d9c2',
              ),
              array (
                'key' => 'field_57a31aa37078f',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a31abf70790',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a1b850a7a4d',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 100,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
              ),
              array (
                'key' => 'field_57b3354a80576',
                'label' => 'Iframe?',
                'name' => 'iframe',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
              ),
              /*
              array (
                'key' => 'field_57b3356080577',
                'label' => 'Iframe Content',
                'name' => 'iframe_content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                  array (
                    array (
                      'field' => 'field_57b3354a80576',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              */
              array (
                'key' => 'field_57b3349c6c167',
                'label' => 'Teaser?',
                'name' => 'teaser',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
              ),
              array (
                'key' => 'field_57a1c090161d9',
                'label' => 'Teaser Color',
                'name' => 'background_color_teaser',
                'type' => 'color_picker',
                'instructions' => 'Teaser Background Color',
                'required' => 0,
                'conditional_logic' => array (
                  array (
                    array (
                      'field' => 'field_57b3349c6c167',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
              ),
              array (
                'key' => 'field_57a1ba2ba7a50',
                'label' => 'Teaser Content',
                'name' => 'content_teaser',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                  array (
                    array (
                      'field' => 'field_57b3349c6c167',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array (
                  'width' => 100,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
            array (
                'key' => '5845a8c9c1925',
                'name' => 'news_module',
                'label' => 'News Module',
                'display' => 'block',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5845a8d2c1926',
                        'label' => 'Category',
                        'name' => 'category',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'category',
                        'field_type' => 'multi_select',
                        'allow_null' => 0,
                        'add_term' => 1,
                        'save_terms' => 0,
                        'load_terms' => 0,
                        'return_format' => 'id',
                        'multiple' => 0,
                    ),
                ),
                'min' => '',
                'max' => '',
            ),
          array (
            'key' => '57a3190d7078d',
            'name' => 'keybenefits',
            'label' => 'Keybenefits',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_57a34feac4a6d',
                'label' => 'Color',
                'name' => 'background_color',
                'type' => 'color_picker',
                'instructions' => 'Background Color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 33,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '#f3d9c2',
              ),
              array (
                'key' => 'field_57a3500cc4a6f',
                'label' => 'Primary Color',
                'name' => 'primary_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 33,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '#eeb181',
              ),
              array (
                'key' => 'field_57a35018c4a70',
                'label' => 'Secondary Color',
                'name' => 'secondary_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 33,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '#eba36f',
              ),
              array (
                'key' => 'field_57a319bb7078e',
                'label' => 'Slideshow',
                'name' => 'gallery',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'min' => 4,
                'max' => '',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          array (
            'key' => '57a35c3a32b55',
            'name' => 'quicklinks_module',
            'label' => 'Quick Links Module',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_57a35c5832b56',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a35c6732b57',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a35c7432b58',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
              ),
              array (
                'key' => 'field_57a35d3a32b5b',
                'label' => 'Columns',
                'name' => 'columns',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 100,
                  'class' => '',
                  'id' => '',
                ),
                'button_label' => 'Add Column',
                'min' => '',
                'max' => '',
                'layouts' => array (
                  array (
                    'key' => '57a35d53b7bee',
                    'name' => 'column',
                    'label' => 'Column',
                    'display' => 'table',
                    'sub_fields' => array (
                      array (
                        'key' => 'field_57a35daa32b5c',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                      ),
                      array (
                        'key' => 'field_57a35de132b5e',
                        'label' => 'Button Link',
                        'name' => 'button_link',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                          'width' => 33,
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                      ),
                      array (
                        'key' => 'field_57a35dbc32b5d',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 0,
                      ),
                    ),
                    'min' => '',
                    'max' => 4,
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          array (
            'key' => '57a1bd26161c3',
            'name' => 'gallery_module',
            'label' => 'Gallery Module',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_57a1bd31161c4',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => 'module_title',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a1bd4e161c5',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => 'module_subtitle',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a1c04e161d8',
                'label' => 'Color',
                'name' => 'background_color',
                'type' => 'color_picker',
                'instructions' => 'Background Color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '#dadfb5',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          array (
            'key' => '57a1bdc8161c7',
            'name' => 'content_module',
            'label' => 'Static Club Card Content Module',
            'display' => 'block',
            'sub_fields' => array (
            ),
            'min' => '',
            'max' => '',
          ),
          array (
            'key' => '57a1bed7161ce',
            'name' => 'contact_module',
            'label' => 'Contact Module',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_57a1bee4161cf',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => 'module_title',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a1beec161d0',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => 'module_subtitle',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57a1c019161d7',
                'label' => 'Color',
                'name' => 'background_color',
                'type' => 'color_picker',
                'instructions' => 'Background color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '#f3d9c2',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          array (
            'key' => '57a1bf10161d1',
            'name' => 'mobile_teaser_module',
            'label' => 'Static Mobile Teaser Module',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_57a1bf24161d2',
                'label' => 'Display',
                'name' => 'display',
                'type' => 'radio',
                'instructions' => 'Customize the content at the General Content Settings.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  'true' => 'Yes',
                  'false' => 'No',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'default',
        ),
        array (
          'param' => 'page',
          'operator' => '!=',
          'value' => '25',
        ),
      ),
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'template-blog.php',
        ),
        array (
          'param' => 'page',
          'operator' => '!=',
          'value' => '25',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'field',
    'hide_on_screen' => array (
      0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array (
    'key' => 'group_57b483bb65fe3',
    'title' => 'Static Page',
    'fields' => array (
      array (
        'key' => 'field_57b483f121a38',
        'label' => 'Static Content',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'The content cannot be edited in CMS.',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page',
          'operator' => '==',
          'value' => '25',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'custom_fields',
      3 => 'discussion',
      4 => 'comments',
      5 => 'revisions',
      6 => 'slug',
      7 => 'author',
      8 => 'format',
      9 => 'page_attributes',
      10 => 'featured_image',
      11 => 'categories',
      12 => 'tags',
      13 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array (
    'key' => 'group_57a0c9f7361bc',
    'title' => 'Trainer Info',
    'fields' => array (
      array (
        'key' => 'field_57ebcfd4d6c53',
        'label' => 'Trainer Profession',
        'name' => 'trainer_profession',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57e5373fc914c',
        'label' => 'Background Color',
        'name' => 'trainer_background_color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array (
        'key' => 'field_57a48e4423db5',
        'label' => 'Phone Number',
        'name' => 'phone_number',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_57a48e5323db6',
        'label' => 'E-Mail Address',
        'name' => 'email_address',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_57ebd36edb49b',
        'label' => 'Setcard',
        'name' => 'setcard',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'trainer',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array (
    'key' => 'group_57ac3ef1c4ed0',
    'title' => 'Trainer Page',
    'fields' => array (
      array (
        'key' => 'field_57ad76b21a4eb',
        'label' => 'Subtitle',
        'name' => 'subtitle',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'template-trainer.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

    acf_add_local_field_group(array (
        'key' => 'group_598c4970889b5',
        'title' => 'Newsletter',
        'fields' => array (
            array (
                'key' => 'field_598c497d5bb50',
                'label' => 'Month and Year',
                'name' => 'month_and_year',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'default_value' => '',
                'placeholder' => 'Januar 2016',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_598c4a895bb51',
                'label' => 'Header Image',
                'name' => 'header_image',
                'type' => 'image',
                'instructions' => 'Recommended width 600px!',
                'required' => 0,
                'conditional_logic' => 0,
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_598c4abf5bb52',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'default_value' => '<p><strong>LIEBE LESERIN, LIEBER LESER,</strong></p><p>wir hoffen Sie hatten einen fitten, gesunden und erfolgreichen Start in das Jahr 2016!</p><p>Wir unterstützen Sie gerne beim Erreichen Ihrer sportlichen Ziele mit vielen verschiedenen Trainingsspecials, Conventions, besonderen Kursangeboten sowie Turnieren in den Bereichen Fitness und Ballsport. Kommen Sie fit durch den Winter und trainieren Sie in unserem neu gestalteten Fitnessbereich mit neuen Geräten und einer großen Functionalfläche.</p><p>Für all diejenigen, die lieber in der Gruppe trainieren ist unsere <strong>7. Fun &amp; Move</strong> Convention am Samstag, den 30. April 2016 genau das richtige. Auch dieses Jahr sind wieder die Top-Presenter aus aller Welt bei uns und zeigen Ihnen die neuesten Tanztrends oder Yoga-Übungen.</p><p>Wir freuen uns auf Ihren Besuch.</p><p><img class="alignnone size-medium wp-image-2620" src="' . get_site_url() . '/wp-content/uploads/2017/08/UnterschriftSara-300x274.png" alt="UnterschriftSara" width="114" height="104" /><br />Herzliche Grüße,<br /> Stephanie Dallmair</p>',
                'tabs' => 'visual',
                'toolbar' => 'basic',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_598c4add5bb53',
                'label' => 'Articles',
                'name' => 'articles',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_598c4af65bb54',
                'min' => '',
                'max' => '',
                'layout' => 'block',
                'button_label' => 'Add Article',
                'sub_fields' => array (
                    array (
                        'key' => 'field_598c4b235bb57',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => 'Strictly 180x160 resolution.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'return_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => 180,
                        'min_height' => 160,
                        'min_size' => '',
                        'max_width' => 180,
                        'max_height' => 160,
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array (
                        'key' => 'field_598c4af65bb54',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => '7. FUN & MOVE CONVENTION',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_598c4bcb5bb58',
                        'label' => 'Subtitle/Date (Optional)',
                        'name' => 'subtitle',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'Samstag, den 30. April 2016',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_598c4b005bb55',
                        'label' => 'Text',
                        'name' => 'text',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => 'Special Guests: Magnus Ringberg (Götenborg), Calvin Wiley (New York), Piero Barbato (Rome) ... und weitere tolle Presenter!',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => 'wpautop',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_598c4b0e5bb56',
                        'label' => 'Mehr Link',
                        'name' => 'link',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => ''
                    )
                )
            )
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

  acf_add_local_field_group(array (
    'key' => 'group_59c0f408632fa',
    'title' => 'Template Settings',
    'fields' => array (
        array (
            'key' => 'field_fouj6uwriexou',
            'label' => 'Subtitle (Optional)',
            'name' => 'subtitle',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
        'key' => 'field_59c0f414b2ea6',
        'label' => 'Category',
        'name' => 'category',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'category',
        'field_type' => 'multi_select',
        'allow_null' => 1,
        'add_term' => 0,
        'save_terms' => 1,
        'load_terms' => 1,
        'return_format' => 'id',
        'multiple' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'template-article.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'featured_image',
    ),
    'active' => 1,
    'description' => '',
  ));

endif;
